import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

// Import Satoshi fonts
const satoshiBold = localFont({
  src: './fonts/Satoshi-Bold.woff2',
  variable: '--font-satoshi-bold',
  weight: '700', // Weight for Bold
});

const satoshiLight = localFont({
  src: './fonts/Satoshi-Light.woff2',
  variable: '--font-satoshi-light',
  weight: '300', // Weight for Light
});

const satoshiMedium = localFont({
  src: './fonts/Satoshi-Medium.woff2',
  variable: '--font-satoshi-medium',
  weight: '500', // Weight for Medium
});

const satoshiRegular = localFont({
  src: './fonts/Satoshi-Regular.woff2',
  variable: '--font-satoshi-regular',
  weight: '400', // Weight for Regular
});

// Metadata for the application
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshiLight.className} ${satoshiRegular.className} ${satoshiMedium.className} ${satoshiBold.className} antialiased bg-[#10100e] text-[#ffffe3]`}
      >
        {children}
      </body>
    </html>
  );
}
