import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import type { Metadata } from 'next';

// Metadata for the applicatio
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <div className="h-screen w-[200px] bg-[#10100e]">
        <Sidebar />
      </div>
      <div className="flex flex-col w-full m-4">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
